// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJ00rWZfECMPuttwIA8agjvuACntbOsA',
    appId: '1:290626860842:web:d1a172cac7da3d7ca8d053',
    messagingSenderId: '290626860842',
    projectId: 'speaking-bus-stop-reminder',
    authDomain: 'speaking-bus-stop-reminder.firebaseapp.com',
    databaseURL: 'https://speaking-bus-stop-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'speaking-bus-stop-reminder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDagEI49B1E6MX3A46UalwvCux_AqPsTzA',
    appId: '1:290626860842:android:9a256cfdd25a92faa8d053',
    messagingSenderId: '290626860842',
    projectId: 'speaking-bus-stop-reminder',
    databaseURL: 'https://speaking-bus-stop-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'speaking-bus-stop-reminder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfk3corcqBJb4Rri26-Pa_mFRs7jdszp4',
    appId: '1:290626860842:ios:29e088c33b2c7eb3a8d053',
    messagingSenderId: '290626860842',
    projectId: 'speaking-bus-stop-reminder',
    databaseURL: 'https://speaking-bus-stop-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'speaking-bus-stop-reminder.appspot.com',
    iosBundleId: 'com.example.sbsr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfk3corcqBJb4Rri26-Pa_mFRs7jdszp4',
    appId: '1:290626860842:ios:c8aa46ae24db9677a8d053',
    messagingSenderId: '290626860842',
    projectId: 'speaking-bus-stop-reminder',
    databaseURL: 'https://speaking-bus-stop-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'speaking-bus-stop-reminder.appspot.com',
    iosBundleId: 'com.example.sbsr.RunnerTests',
  );
}
